//
//  Syllable+Info.swift
//  Canto
//
//  Created by Resonance on 10/3/2019.
//  Copyright © 2019 AppAppWorks. All rights reserved.
//

import Foundation

extension Syllable {
    var info: Info {
        switch self {
        case .aa1: return .aa1
        case .aa2: return .aa2
        case .aa3: return .aa3
        case .aa4: return .aa4
        case .aa5: return .aa5
        case .aa6: return .aa6
        case .aai1: return .aai1
        case .aai2: return .aai2
        case .aai3: return .aai3
        case .aai4: return .aai4
        case .aai5: return .aai5
        case .aai6: return .aai6
        case .aak1: return .aak1
        case .aak2: return .aak2
        case .aak3: return .aak3
        case .aak6: return .aak6
        case .aam1: return .aam1
        case .aam4: return .aam4
        case .aan2: return .aan2
        case .aan3: return .aan3
        case .aan4: return .aan4
        case .aan5: return .aan5
        case .aan6: return .aan6
        case .aang1: return .aang1
        case .aang2: return .aang2
        case .aang6: return .aang6
        case .aap2: return .aap2
        case .aap3: return .aap3
        case .aat1: return .aat1
        case .aat2: return .aat2
        case .aat3: return .aat3
        case .aat6: return .aat6
        case .aau1: return .aau1
        case .aau2: return .aau2
        case .aau3: return .aau3
        case .aau4: return .aau4
        case .aau5: return .aau5
        case .aau6: return .aau6
        case .ai1: return .ai1
        case .ai2: return .ai2
        case .ai3: return .ai3
        case .ai4: return .ai4
        case .ai5: return .ai5
        case .ai6: return .ai6
        case .ak1: return .ak1
        case .am1: return .am1
        case .am2: return .am2
        case .am3: return .am3
        case .am4: return .am4
        case .am5: return .am5
        case .am6: return .am6
        case .an1: return .an1
        case .an2: return .an2
        case .an3: return .an3
        case .an4: return .an4
        case .an6: return .an6
        case .ang1: return .ang1
        case .ang2: return .ang2
        case .ang3: return .ang3
        case .ap1: return .ap1
        case .ap6: return .ap6
        case .at1: return .at1
        case .at6: return .at6
        case .au1: return .au1
        case .au2: return .au2
        case .au3: return .au3
        case .au4: return .au4
        case .au5: return .au5
        case .au6: return .au6
        case .baa1: return .baa1
        case .baa2: return .baa2
        case .baa3: return .baa3
        case .baa4: return .baa4
        case .baa6: return .baa6
        case .baai1: return .baai1
        case .baai2: return .baai2
        case .baai3: return .baai3
        case .baai6: return .baai6
        case .baak1: return .baak1
        case .baak2: return .baak2
        case .baak3: return .baak3
        case .baak6: return .baak6
        case .baan1: return .baan1
        case .baan2: return .baan2
        case .baan3: return .baan3
        case .baan6: return .baan6
        case .baang1: return .baang1
        case .baang4: return .baang4
        case .baang6: return .baang6
        case .baat2: return .baat2
        case .baat3: return .baat3
        case .baat6: return .baat6
        case .baau1: return .baau1
        case .baau2: return .baau2
        case .baau3: return .baau3
        case .baau6: return .baau6
        case .bai1: return .bai1
        case .bai2: return .bai2
        case .bai3: return .bai3
        case .bai6: return .bai6
        case .bak1: return .bak1
        case .bam1: return .bam1
        case .ban1: return .ban1
        case .ban2: return .ban2
        case .ban3: return .ban3
        case .ban6: return .ban6
        case .bang1: return .bang1
        case .bang2: return .bang2
        case .bang6: return .bang6
        case .bat1: return .bat1
        case .bat3: return .bat3
        case .bat6: return .bat6
        case .bau2: return .bau2
        case .bau6: return .bau6
        case .be1: return .be1
        case .be4: return .be4
        case .be6: return .be6
        case .bei1: return .bei1
        case .bei2: return .bei2
        case .bei3: return .bei3
        case .bei4: return .bei4
        case .bei6: return .bei6
        case .bek3: return .bek3
        case .ben1: return .ben1
        case .beng2: return .beng2
        case .beng3: return .beng3
        case .beng6: return .beng6
        case .bi1: return .bi1
        case .bi4: return .bi4
        case .bik1: return .bik1
        case .bik3: return .bik3
        case .bik6: return .bik6
        case .bin1: return .bin1
        case .bin2: return .bin2
        case .bin3: return .bin3
        case .bin6: return .bin6
        case .bing1: return .bing1
        case .bing2: return .bing2
        case .bing3: return .bing3
        case .bing4: return .bing4
        case .bing6: return .bing6
        case .bit1: return .bit1
        case .bit3: return .bit3
        case .bit6: return .bit6
        case .biu1: return .biu1
        case .biu2: return .biu2
        case .biu3: return .biu3
        case .biu6: return .biu6
        case .bo1: return .bo1
        case .bo2: return .bo2
        case .bo3: return .bo3
        case .bok1: return .bok1
        case .bok2: return .bok2
        case .bok3: return .bok3
        case .bok6: return .bok6
        case .bong1: return .bong1
        case .bong2: return .bong2
        case .bong3: return .bong3
        case .bong4: return .bong4
        case .bong6: return .bong6
        case .bou1: return .bou1
        case .bou2: return .bou2
        case .bou3: return .bou3
        case .bou6: return .bou6
        case .bui1: return .bui1
        case .bui2: return .bui2
        case .bui3: return .bui3
        case .bui6: return .bui6
        case .buk1: return .buk1
        case .buk6: return .buk6
        case .bun1: return .bun1
        case .bun2: return .bun2
        case .bun3: return .bun3
        case .bun5: return .bun5
        case .bun6: return .bun6
        case .bung2: return .bung2
        case .bung3: return .bung3
        case .bung6: return .bung6
        case .but1: return .but1
        case .but2: return .but2
        case .but3: return .but3
        case .but6: return .but6
        case .caa1: return .caa1
        case .caa2: return .caa2
        case .caa3: return .caa3
        case .caa4: return .caa4
        case .caa5: return .caa5
        case .caai1: return .caai1
        case .caai2: return .caai2
        case .caai3: return .caai3
        case .caai4: return .caai4
        case .caak1: return .caak1
        case .caak2: return .caak2
        case .caak3: return .caak3
        case .caak6: return .caak6
        case .caam1: return .caam1
        case .caam2: return .caam2
        case .caam3: return .caam3
        case .caam4: return .caam4
        case .caam5: return .caam5
        case .caan1: return .caan1
        case .caan2: return .caan2
        case .caan3: return .caan3
        case .caan4: return .caan4
        case .caang1: return .caang1
        case .caang2: return .caang2
        case .caang3: return .caang3
        case .caang4: return .caang4
        case .caap2: return .caap2
        case .caap3: return .caap3
        case .caat1: return .caat1
        case .caat2: return .caat2
        case .caat3: return .caat3
        case .caau1: return .caau1
        case .caau2: return .caau2
        case .caau3: return .caau3
        case .caau4: return .caau4
        case .cai1: return .cai1
        case .cai2: return .cai2
        case .cai3: return .cai3
        case .cai4: return .cai4
        case .cai5: return .cai5
        case .cak1: return .cak1
        case .cam1: return .cam1
        case .cam2: return .cam2
        case .cam3: return .cam3
        case .cam4: return .cam4
        case .cam5: return .cam5
        case .can1: return .can1
        case .can2: return .can2
        case .can3: return .can3
        case .can4: return .can4
        case .cang1: return .cang1
        case .cang3: return .cang3
        case .cang4: return .cang4
        case .cap1: return .cap1
        case .cat1: return .cat1
        case .cat6: return .cat6
        case .cau1: return .cau1
        case .cau2: return .cau2
        case .cau3: return .cau3
        case .cau4: return .cau4
        case .ce1: return .ce1
        case .ce2: return .ce2
        case .ce3: return .ce3
        case .ce4: return .ce4
        case .ce5: return .ce5
        case .ce6: return .ce6
        case .cek1: return .cek1
        case .cek2: return .cek2
        case .cek3: return .cek3
        case .ceng1: return .ceng1
        case .ceng2: return .ceng2
        case .ceng4: return .ceng4
        case .ceoi1: return .ceoi1
        case .ceoi2: return .ceoi2
        case .ceoi3: return .ceoi3
        case .ceoi4: return .ceoi4
        case .ceon1: return .ceon1
        case .ceon2: return .ceon2
        case .ceon4: return .ceon4
        case .ceot1: return .ceot1
        case .ci1: return .ci1
        case .ci2: return .ci2
        case .ci3: return .ci3
        case .ci4: return .ci4
        case .ci5: return .ci5
        case .cik1: return .cik1
        case .cik3: return .cik3
        case .cim1: return .cim1
        case .cim2: return .cim2
        case .cim3: return .cim3
        case .cim4: return .cim4
        case .cim5: return .cim5
        case .cin1: return .cin1
        case .cin2: return .cin2
        case .cin3: return .cin3
        case .cin4: return .cin4
        case .cin5: return .cin5
        case .cing1: return .cing1
        case .cing2: return .cing2
        case .cing3: return .cing3
        case .cing4: return .cing4
        case .cip1: return .cip1
        case .cip3: return .cip3
        case .cit1: return .cit1
        case .cit3: return .cit3
        case .ciu1: return .ciu1
        case .ciu2: return .ciu2
        case .ciu3: return .ciu3
        case .ciu4: return .ciu4
        case .ciu5: return .ciu5
        case .ciu6: return .ciu6
        case .co1: return .co1
        case .co2: return .co2
        case .co3: return .co3
        case .co4: return .co4
        case .co5: return .co5
        case .coek3: return .coek3
        case .coeng1: return .coeng1
        case .coeng2: return .coeng2
        case .coeng3: return .coeng3
        case .coeng4: return .coeng4
        case .coi1: return .coi1
        case .coi2: return .coi2
        case .coi3: return .coi3
        case .coi4: return .coi4
        case .cok3: return .cok3
        case .cong1: return .cong1
        case .cong2: return .cong2
        case .cong3: return .cong3
        case .cong4: return .cong4
        case .cou1: return .cou1
        case .cou2: return .cou2
        case .cou3: return .cou3
        case .cou4: return .cou4
        case .cou5: return .cou5
        case .cuk1: return .cuk1
        case .cuk6: return .cuk6
        case .cung1: return .cung1
        case .cung2: return .cung2
        case .cung3: return .cung3
        case .cung4: return .cung4
        case .cung5: return .cung5
        case .cyu2: return .cyu2
        case .cyu3: return .cyu3
        case .cyu4: return .cyu4
        case .cyu5: return .cyu5
        case .cyun1: return .cyun1
        case .cyun2: return .cyun2
        case .cyun3: return .cyun3
        case .cyun4: return .cyun4
        case .cyut1: return .cyut1
        case .cyut3: return .cyut3
        case .cyut6: return .cyut6
        case .daa1: return .daa1
        case .daa2: return .daa2
        case .daai1: return .daai1
        case .daai2: return .daai2
        case .daai3: return .daai3
        case .daai6: return .daai6
        case .daak1: return .daak1
        case .daam1: return .daam1
        case .daam2: return .daam2
        case .daam3: return .daam3
        case .daam5: return .daam5
        case .daam6: return .daam6
        case .daan1: return .daan1
        case .daan2: return .daan2
        case .daan3: return .daan3
        case .daan5: return .daan5
        case .daan6: return .daan6
        case .daap1: return .daap1
        case .daap3: return .daap3
        case .daap6: return .daap6
        case .daat3: return .daat3
        case .daat6: return .daat6
        case .dai1: return .dai1
        case .dai2: return .dai2
        case .dai3: return .dai3
        case .dai4: return .dai4
        case .dai6: return .dai6
        case .dak1: return .dak1
        case .dak6: return .dak6
        case .dam1: return .dam1
        case .dam2: return .dam2
        case .dam3: return .dam3
        case .dam4: return .dam4
        case .dam6: return .dam6
        case .dan1: return .dan1
        case .dan2: return .dan2
        case .dan3: return .dan3
        case .dan6: return .dan6
        case .dang1: return .dang1
        case .dang2: return .dang2
        case .dang3: return .dang3
        case .dang6: return .dang6
        case .dap1: return .dap1
        case .dap6: return .dap6
        case .dat1: return .dat1
        case .dat6: return .dat6
        case .dau1: return .dau1
        case .dau2: return .dau2
        case .dau3: return .dau3
        case .dau4: return .dau4
        case .dau6: return .dau6
        case .de1: return .de1
        case .de2: return .de2
        case .de4: return .de4
        case .dei2: return .dei2
        case .dei6: return .dei6
        case .dek2: return .dek2
        case .dek3: return .dek3
        case .dek6: return .dek6
        case .deng1: return .deng1
        case .deng2: return .deng2
        case .deng3: return .deng3
        case .deng6: return .deng6
        case .deoi1: return .deoi1
        case .deoi2: return .deoi2
        case .deoi3: return .deoi3
        case .deoi6: return .deoi6
        case .deon1: return .deon1
        case .deon2: return .deon2
        case .deon6: return .deon6
        case .deot1: return .deot1
        case .deu6: return .deu6
        case .di1: return .di1
        case .di2: return .di2
        case .di4: return .di4
        case .dik1: return .dik1
        case .dik6: return .dik6
        case .dim1: return .dim1
        case .dim2: return .dim2
        case .dim3: return .dim3
        case .dim6: return .dim6
        case .din1: return .din1
        case .din2: return .din2
        case .din3: return .din3
        case .din6: return .din6
        case .ding1: return .ding1
        case .ding2: return .ding2
        case .ding3: return .ding3
        case .ding6: return .ding6
        case .dip2: return .dip2
        case .dip3: return .dip3
        case .dip6: return .dip6
        case .dit1: return .dit1
        case .dit3: return .dit3
        case .dit6: return .dit6
        case .diu1: return .diu1
        case .diu2: return .diu2
        case .diu3: return .diu3
        case .diu4: return .diu4
        case .diu6: return .diu6
        case .do1: return .do1
        case .do2: return .do2
        case .do3: return .do3
        case .do6: return .do6
        case .doe2: return .doe2
        case .doe3: return .doe3
        case .doe4: return .doe4
        case .doe6: return .doe6
        case .doek1: return .doek1
        case .doek3: return .doek3
        case .doeng1: return .doeng1
        case .doi2: return .doi2
        case .doi6: return .doi6
        case .dok6: return .dok6
        case .dong1: return .dong1
        case .dong2: return .dong2
        case .dong3: return .dong3
        case .dong6: return .dong6
        case .dou1: return .dou1
        case .dou2: return .dou2
        case .dou3: return .dou3
        case .dou6: return .dou6
        case .du1: return .du1
        case .duk1: return .duk1
        case .duk2: return .duk2
        case .duk6: return .duk6
        case .dung1: return .dung1
        case .dung2: return .dung2
        case .dung3: return .dung3
        case .dung6: return .dung6
        case .dut1: return .dut1
        case .dyun1: return .dyun1
        case .dyun2: return .dyun2
        case .dyun3: return .dyun3
        case .dyun6: return .dyun6
        case .dyut1: return .dyut1
        case .dyut3: return .dyut3
        case .dyut6: return .dyut6
        case .e4: return .e4
        case .e6: return .e6
        case .ei1: return .ei1
        case .ei3: return .ei3
        case .ei6: return .ei6
        case .em1: return .em1
        case .en1: return .en1
        case .eot1: return .eot1
        case .eu4: return .eu4
        case .faa1: return .faa1
        case .faa2: return .faa2
        case .faa3: return .faa3
        case .faa4: return .faa4
        case .faai1: return .faai1
        case .faai2: return .faai2
        case .faai3: return .faai3
        case .faak3: return .faak3
        case .faan1: return .faan1
        case .faan2: return .faan2
        case .faan3: return .faan3
        case .faan4: return .faan4
        case .faan5: return .faan5
        case .faan6: return .faan6
        case .faat2: return .faat2
        case .faat3: return .faat3
        case .fai1: return .fai1
        case .fai2: return .fai2
        case .fai3: return .fai3
        case .fai6: return .fai6
        case .fan1: return .fan1
        case .fan2: return .fan2
        case .fan3: return .fan3
        case .fan4: return .fan4
        case .fan5: return .fan5
        case .fan6: return .fan6
        case .fang4: return .fang4
        case .fang6: return .fang6
        case .fat1: return .fat1
        case .fat6: return .fat6
        case .fau1: return .fau1
        case .fau2: return .fau2
        case .fau4: return .fau4
        case .fau6: return .fau6
        case .fe1: return .fe1
        case .fe3: return .fe3
        case .fe4: return .fe4
        case .fei1: return .fei1
        case .fei2: return .fei2
        case .fei4: return .fei4
        case .fei6: return .fei6
        case .fen1: return .fen1
        case .fet1: return .fet1
        case .fi1: return .fi1
        case .fik1: return .fik1
        case .fing3: return .fing3
        case .fing6: return .fing6
        case .fit1: return .fit1
        case .fiu1: return .fiu1
        case .fiu3: return .fiu3
        case .fo1: return .fo1
        case .fo2: return .fo2
        case .fo3: return .fo3
        case .fok3: return .fok3
        case .fong1: return .fong1
        case .fong2: return .fong2
        case .fong3: return .fong3
        case .fong4: return .fong4
        case .fong6: return .fong6
        case .fu1: return .fu1
        case .fu2: return .fu2
        case .fu3: return .fu3
        case .fu4: return .fu4
        case .fu5: return .fu5
        case .fu6: return .fu6
        case .fui1: return .fui1
        case .fui2: return .fui2
        case .fui3: return .fui3
        case .fuk1: return .fuk1
        case .fuk2: return .fuk2
        case .fuk6: return .fuk6
        case .fun1: return .fun1
        case .fun2: return .fun2
        case .fung1: return .fung1
        case .fung2: return .fung2
        case .fung3: return .fung3
        case .fung4: return .fung4
        case .fung6: return .fung6
        case .fut3: return .fut3
        case .gaa1: return .gaa1
        case .gaa2: return .gaa2
        case .gaa3: return .gaa3
        case .gaa4: return .gaa4
        case .gaa5: return .gaa5
        case .gaai1: return .gaai1
        case .gaai2: return .gaai2
        case .gaai3: return .gaai3
        case .gaak2: return .gaak2
        case .gaak3: return .gaak3
        case .gaam1: return .gaam1
        case .gaam2: return .gaam2
        case .gaam3: return .gaam3
        case .gaan1: return .gaan1
        case .gaan2: return .gaan2
        case .gaan3: return .gaan3
        case .gaang1: return .gaang1
        case .gaang3: return .gaang3
        case .gaap2: return .gaap2
        case .gaap3: return .gaap3
        case .gaat3: return .gaat3
        case .gaat6: return .gaat6
        case .gaau1: return .gaau1
        case .gaau2: return .gaau2
        case .gaau3: return .gaau3
        case .gaau4: return .gaau4
        case .gai1: return .gai1
        case .gai2: return .gai2
        case .gai3: return .gai3
        case .gai6: return .gai6
        case .gak1: return .gak1
        case .gam1: return .gam1
        case .gam2: return .gam2
        case .gam3: return .gam3
        case .gam6: return .gam6
        case .gan1: return .gan1
        case .gan2: return .gan2
        case .gan3: return .gan3
        case .gan6: return .gan6
        case .gang1: return .gang1
        case .gang2: return .gang2
        case .gang3: return .gang3
        case .gap1: return .gap1
        case .gap2: return .gap2
        case .gap3: return .gap3
        case .gap6: return .gap6
        case .gat1: return .gat1
        case .gat3: return .gat3
        case .gat6: return .gat6
        case .gau1: return .gau1
        case .gau2: return .gau2
        case .gau3: return .gau3
        case .gau6: return .gau6
        case .ge2: return .ge2
        case .ge3: return .ge3
        case .gei1: return .gei1
        case .gei2: return .gei2
        case .gei3: return .gei3
        case .gei6: return .gei6
        case .gek1: return .gek1
        case .geng1: return .geng1
        case .geng2: return .geng2
        case .geng3: return .geng3
        case .geng6: return .geng6
        case .geoi1: return .geoi1
        case .geoi2: return .geoi2
        case .geoi3: return .geoi3
        case .geoi6: return .geoi6
        case .gep1: return .gep1
        case .gep6: return .gep6
        case .gi1: return .gi1
        case .gik1: return .gik1
        case .gik6: return .gik6
        case .gim1: return .gim1
        case .gim2: return .gim2
        case .gim3: return .gim3
        case .gim6: return .gim6
        case .gin1: return .gin1
        case .gin2: return .gin2
        case .gin3: return .gin3
        case .gin6: return .gin6
        case .ging1: return .ging1
        case .ging2: return .ging2
        case .ging3: return .ging3
        case .ging6: return .ging6
        case .gip1: return .gip1
        case .gip2: return .gip2
        case .gip3: return .gip3
        case .gip6: return .gip6
        case .git3: return .git3
        case .git6: return .git6
        case .giu1: return .giu1
        case .giu2: return .giu2
        case .giu3: return .giu3
        case .giu4: return .giu4
        case .giu6: return .giu6
        case .go1: return .go1
        case .go2: return .go2
        case .go3: return .go3
        case .go4: return .go4
        case .go6: return .go6
        case .goe1: return .goe1
        case .goe3: return .goe3
        case .goe4: return .goe4
        case .goek2: return .goek2
        case .goek3: return .goek3
        case .goeng1: return .goeng1
        case .goeng2: return .goeng2
        case .goeng6: return .goeng6
        case .goi1: return .goi1
        case .goi2: return .goi2
        case .goi3: return .goi3
        case .gok1: return .gok1
        case .gok2: return .gok2
        case .gok3: return .gok3
        case .gok6: return .gok6
        case .gon1: return .gon1
        case .gon2: return .gon2
        case .gon3: return .gon3
        case .gong1: return .gong1
        case .gong2: return .gong2
        case .gong3: return .gong3
        case .gong6: return .gong6
        case .got2: return .got2
        case .got3: return .got3
        case .gou1: return .gou1
        case .gou2: return .gou2
        case .gou3: return .gou3
        case .gu1: return .gu1
        case .gu2: return .gu2
        case .gu3: return .gu3
        case .gu4: return .gu4
        case .gui3: return .gui3
        case .gui6: return .gui6
        case .guk1: return .guk1
        case .guk2: return .guk2
        case .guk6: return .guk6
        case .gun1: return .gun1
        case .gun2: return .gun2
        case .gun3: return .gun3
        case .gung1: return .gung1
        case .gung2: return .gung2
        case .gung3: return .gung3
        case .gung4: return .gung4
        case .gung6: return .gung6
        case .gut2: return .gut2
        case .gut3: return .gut3
        case .gut4: return .gut4
        case .gut6: return .gut6
        case .gwaa1: return .gwaa1
        case .gwaa2: return .gwaa2
        case .gwaa3: return .gwaa3
        case .gwaai1: return .gwaai1
        case .gwaai2: return .gwaai2
        case .gwaai3: return .gwaai3
        case .gwaak3: return .gwaak3
        case .gwaan1: return .gwaan1
        case .gwaan3: return .gwaan3
        case .gwaang2: return .gwaang2
        case .gwaang6: return .gwaang6
        case .gwaat2: return .gwaat2
        case .gwaat3: return .gwaat3
        case .gwai1: return .gwai1
        case .gwai2: return .gwai2
        case .gwai3: return .gwai3
        case .gwai6: return .gwai6
        case .gwan1: return .gwan1
        case .gwan2: return .gwan2
        case .gwan3: return .gwan3
        case .gwan6: return .gwan6
        case .gwang1: return .gwang1
        case .gwang2: return .gwang2
        case .gwat1: return .gwat1
        case .gwat6: return .gwat6
        case .gwe1: return .gwe1
        case .gwik1: return .gwik1
        case .gwing1: return .gwing1
        case .gwing2: return .gwing2
        case .gwing3: return .gwing3
        case .gwit1: return .gwit1
        case .gwit3: return .gwit3
        case .gwo1: return .gwo1
        case .gwo2: return .gwo2
        case .gwo3: return .gwo3
        case .gwok3: return .gwok3
        case .gwong1: return .gwong1
        case .gwong2: return .gwong2
        case .gwong3: return .gwong3
        case .gwu1: return .gwu1
        case .gwu2: return .gwu2
        case .gwu3: return .gwu3
        case .gwui3: return .gwui3
        case .gwui6: return .gwui6
        case .gwun1: return .gwun1
        case .gwun2: return .gwun2
        case .gwun3: return .gwun3
        case .gwut2: return .gwut2
        case .gwut3: return .gwut3
        case .gwut4: return .gwut4
        case .gwut6: return .gwut6
        case .gyun1: return .gyun1
        case .gyun2: return .gyun2
        case .gyun3: return .gyun3
        case .gyun6: return .gyun6
        case .gyut3: return .gyut3
        case .gyut6: return .gyut6
        case .haa1: return .haa1
        case .haa2: return .haa2
        case .haa3: return .haa3
        case .haa4: return .haa4
        case .haa5: return .haa5
        case .haa6: return .haa6
        case .haai1: return .haai1
        case .haai2: return .haai2
        case .haai3: return .haai3
        case .haai4: return .haai4
        case .haai5: return .haai5
        case .haai6: return .haai6
        case .haak1: return .haak1
        case .haak2: return .haak2
        case .haak3: return .haak3
        case .haak6: return .haak6
        case .haam1: return .haam1
        case .haam2: return .haam2
        case .haam3: return .haam3
        case .haam4: return .haam4
        case .haam5: return .haam5
        case .haam6: return .haam6
        case .haan1: return .haan1
        case .haan2: return .haan2
        case .haan4: return .haan4
        case .haan5: return .haan5
        case .haan6: return .haan6
        case .haang1: return .haang1
        case .haang2: return .haang2
        case .haang4: return .haang4
        case .haap3: return .haap3
        case .haap6: return .haap6
        case .haau1: return .haau1
        case .haau2: return .haau2
        case .haau3: return .haau3
        case .haau4: return .haau4
        case .haau6: return .haau6
        case .hai1: return .hai1
        case .hai2: return .hai2
        case .hai3: return .hai3
        case .hai4: return .hai4
        case .hai5: return .hai5
        case .hai6: return .hai6
        case .hak1: return .hak1
        case .ham1: return .ham1
        case .ham2: return .ham2
        case .ham3: return .ham3
        case .ham4: return .ham4
        case .ham5: return .ham5
        case .ham6: return .ham6
        case .han2: return .han2
        case .han4: return .han4
        case .han6: return .han6
        case .hang1: return .hang1
        case .hang2: return .hang2
        case .hang4: return .hang4
        case .hang5: return .hang5
        case .hang6: return .hang6
        case .hap1: return .hap1
        case .hap2: return .hap2
        case .hap6: return .hap6
        case .hat1: return .hat1
        case .hat6: return .hat6
        case .hau1: return .hau1
        case .hau2: return .hau2
        case .hau3: return .hau3
        case .hau4: return .hau4
        case .hau5: return .hau5
        case .hau6: return .hau6
        case .he2: return .he2
        case .he3: return .he3
        case .hei1: return .hei1
        case .hei2: return .hei2
        case .hei3: return .hei3
        case .hek3: return .hek3
        case .heng1: return .heng1
        case .heng6: return .heng6
        case .heoi1: return .heoi1
        case .heoi2: return .heoi2
        case .heoi3: return .heoi3
        case .heoi5: return .heoi5
        case .hi1: return .hi1
        case .hik1: return .hik1
        case .him1: return .him1
        case .him2: return .him2
        case .him3: return .him3
        case .hin1: return .hin1
        case .hin2: return .hin2
        case .hin3: return .hin3
        case .hing1: return .hing1
        case .hing2: return .hing2
        case .hing3: return .hing3
        case .hing5: return .hing5
        case .hip3: return .hip3
        case .hip6: return .hip6
        case .hit3: return .hit3
        case .hiu1: return .hiu1
        case .hiu2: return .hiu2
        case .hiu3: return .hiu3
        case .hiu4: return .hiu4
        case .hm1: return .hm1
        case .hm6: return .hm6
        case .hng6: return .hng6
        case .ho1: return .ho1
        case .ho2: return .ho2
        case .ho3: return .ho3
        case .ho4: return .ho4
        case .ho6: return .ho6
        case .hoe1: return .hoe1
        case .hoe4: return .hoe4
        case .hoeng1: return .hoeng1
        case .hoeng2: return .hoeng2
        case .hoeng3: return .hoeng3
        case .hoi1: return .hoi1
        case .hoi2: return .hoi2
        case .hoi3: return .hoi3
        case .hoi4: return .hoi4
        case .hoi5: return .hoi5
        case .hoi6: return .hoi6
        case .hok2: return .hok2
        case .hok3: return .hok3
        case .hok6: return .hok6
        case .hon1: return .hon1
        case .hon2: return .hon2
        case .hon3: return .hon3
        case .hon4: return .hon4
        case .hon5: return .hon5
        case .hon6: return .hon6
        case .hong1: return .hong1
        case .hong2: return .hong2
        case .hong3: return .hong3
        case .hong4: return .hong4
        case .hong5: return .hong5
        case .hong6: return .hong6
        case .hot3: return .hot3
        case .hot6: return .hot6
        case .hou1: return .hou1
        case .hou2: return .hou2
        case .hou3: return .hou3
        case .hou4: return .hou4
        case .hou6: return .hou6
        case .huk1: return .huk1
        case .huk6: return .huk6
        case .hung1: return .hung1
        case .hung2: return .hung2
        case .hung3: return .hung3
        case .hung4: return .hung4
        case .hung6: return .hung6
        case .hyun1: return .hyun1
        case .hyun2: return .hyun2
        case .hyun3: return .hyun3
        case .hyut3: return .hyut3
        case .ik1: return .ik1
        case .it6: return .it6
        case .jaa1: return .jaa1
        case .jaa2: return .jaa2
        case .jaa3: return .jaa3
        case .jaa4: return .jaa4
        case .jaa5: return .jaa5
        case .jaa6: return .jaa6
        case .jaai2: return .jaai2
        case .jaai5: return .jaai5
        case .jaak3: return .jaak3
        case .jaang3: return .jaang3
        case .jaap3: return .jaap3
        case .jaau1: return .jaau1
        case .jai1: return .jai1
        case .jai4: return .jai4
        case .jai5: return .jai5
        case .jai6: return .jai6
        case .jam1: return .jam1
        case .jam2: return .jam2
        case .jam3: return .jam3
        case .jam4: return .jam4
        case .jam5: return .jam5
        case .jam6: return .jam6
        case .jan1: return .jan1
        case .jan2: return .jan2
        case .jan3: return .jan3
        case .jan4: return .jan4
        case .jan5: return .jan5
        case .jan6: return .jan6
        case .jap1: return .jap1
        case .jap6: return .jap6
        case .jat1: return .jat1
        case .jat2: return .jat2
        case .jat6: return .jat6
        case .jau1: return .jau1
        case .jau2: return .jau2
        case .jau3: return .jau3
        case .jau4: return .jau4
        case .jau5: return .jau5
        case .jau6: return .jau6
        case .je1: return .je1
        case .je2: return .je2
        case .je4: return .je4
        case .je5: return .je5
        case .je6: return .je6
        case .jeng4: return .jeng4
        case .jeoi1: return .jeoi1
        case .jeoi4: return .jeoi4
        case .jeoi5: return .jeoi5
        case .jeoi6: return .jeoi6
        case .jeon2: return .jeon2
        case .jeon6: return .jeon6
        case .ji1: return .ji1
        case .ji2: return .ji2
        case .ji3: return .ji3
        case .ji4: return .ji4
        case .ji5: return .ji5
        case .ji6: return .ji6
        case .jik1: return .jik1
        case .jik2: return .jik2
        case .jik6: return .jik6
        case .jim1: return .jim1
        case .jim2: return .jim2
        case .jim3: return .jim3
        case .jim4: return .jim4
        case .jim5: return .jim5
        case .jim6: return .jim6
        case .jin1: return .jin1
        case .jin2: return .jin2
        case .jin3: return .jin3
        case .jin4: return .jin4
        case .jin5: return .jin5
        case .jin6: return .jin6
        case .jing1: return .jing1
        case .jing2: return .jing2
        case .jing3: return .jing3
        case .jing4: return .jing4
        case .jing5: return .jing5
        case .jing6: return .jing6
        case .jip2: return .jip2
        case .jip3: return .jip3
        case .jip6: return .jip6
        case .jit2: return .jit2
        case .jit3: return .jit3
        case .jit6: return .jit6
        case .jiu1: return .jiu1
        case .jiu2: return .jiu2
        case .jiu3: return .jiu3
        case .jiu4: return .jiu4
        case .jiu5: return .jiu5
        case .jiu6: return .jiu6
        case .jo1: return .jo1
        case .joek2: return .joek2
        case .joek3: return .joek3
        case .joek6: return .joek6
        case .joeng1: return .joeng1
        case .joeng2: return .joeng2
        case .joeng3: return .joeng3
        case .joeng4: return .joeng4
        case .joeng5: return .joeng5
        case .joeng6: return .joeng6
        case .juk1: return .juk1
        case .juk2: return .juk2
        case .juk6: return .juk6
        case .jung1: return .jung1
        case .jung2: return .jung2
        case .jung4: return .jung4
        case .jung5: return .jung5
        case .jung6: return .jung6
        case .jyu1: return .jyu1
        case .jyu2: return .jyu2
        case .jyu3: return .jyu3
        case .jyu4: return .jyu4
        case .jyu5: return .jyu5
        case .jyu6: return .jyu6
        case .jyun1: return .jyun1
        case .jyun2: return .jyun2
        case .jyun3: return .jyun3
        case .jyun4: return .jyun4
        case .jyun5: return .jyun5
        case .jyun6: return .jyun6
        case .jyut2: return .jyut2
        case .jyut3: return .jyut3
        case .jyut6: return .jyut6
        case .kaa1: return .kaa1
        case .kaa2: return .kaa2
        case .kaa3: return .kaa3
        case .kaa4: return .kaa4
        case .kaai2: return .kaai2
        case .kaai3: return .kaai3
        case .kaai5: return .kaai5
        case .kaak1: return .kaak1
        case .kaak3: return .kaak3
        case .kaam5: return .kaam5
        case .kaang1: return .kaang1
        case .kaat1: return .kaat1
        case .kaat3: return .kaat3
        case .kaau3: return .kaau3
        case .kai1: return .kai1
        case .kai2: return .kai2
        case .kai3: return .kai3
        case .kak1: return .kak1
        case .kam1: return .kam1
        case .kam2: return .kam2
        case .kam4: return .kam4
        case .kam5: return .kam5
        case .kam6: return .kam6
        case .kan2: return .kan2
        case .kan4: return .kan4
        case .kan5: return .kan5
        case .kang1: return .kang1
        case .kang2: return .kang2
        case .kang3: return .kang3
        case .kap1: return .kap1
        case .kap6: return .kap6
        case .kat1: return .kat1
        case .kau1: return .kau1
        case .kau2: return .kau2
        case .kau3: return .kau3
        case .kau4: return .kau4
        case .kau5: return .kau5
        case .ke1: return .ke1
        case .ke2: return .ke2
        case .ke4: return .ke4
        case .kei1: return .kei1
        case .kei2: return .kei2
        case .kei3: return .kei3
        case .kei4: return .kei4
        case .kei5: return .kei5
        case .kek1: return .kek1
        case .kek6: return .kek6
        case .kem1: return .kem1
        case .ken1: return .ken1
        case .keng1: return .keng1
        case .keoi1: return .keoi1
        case .keoi2: return .keoi2
        case .keoi4: return .keoi4
        case .keoi5: return .keoi5
        case .kep1: return .kep1
        case .ki1: return .ki1
        case .kik1: return .kik1
        case .kim2: return .kim2
        case .kim4: return .kim4
        case .kin2: return .kin2
        case .kin4: return .kin4
        case .king1: return .king1
        case .king2: return .king2
        case .king4: return .king4
        case .kip1: return .kip1
        case .kit3: return .kit3
        case .kiu1: return .kiu1
        case .kiu2: return .kiu2
        case .kiu3: return .kiu3
        case .kiu4: return .kiu4
        case .kiu5: return .kiu5
        case .ko1: return .ko1
        case .koe1: return .koe1
        case .koe4: return .koe4
        case .koek3: return .koek3
        case .koek6: return .koek6
        case .koeng2: return .koeng2
        case .koeng4: return .koeng4
        case .koeng5: return .koeng5
        case .koeng6: return .koeng6
        case .koi2: return .koi2
        case .koi3: return .koi3
        case .kok1: return .kok1
        case .kok3: return .kok3
        case .kon1: return .kon1
        case .kon3: return .kon3
        case .kong1: return .kong1
        case .kong2: return .kong2
        case .kong3: return .kong3
        case .kong4: return .kong4
        case .ku1: return .ku1
        case .kui2: return .kui2
        case .kui3: return .kui3
        case .kuk1: return .kuk1
        case .kung4: return .kung4
        case .kut3: return .kut3
        case .kwaa1: return .kwaa1
        case .kwaa2: return .kwaa2
        case .kwaa3: return .kwaa3
        case .kwaai3: return .kwaai3
        case .kwaai5: return .kwaai5
        case .kwaak1: return .kwaak1
        case .kwaak3: return .kwaak3
        case .kwaang1: return .kwaang1
        case .kwaang3: return .kwaang3
        case .kwaat1: return .kwaat1
        case .kwai1: return .kwai1
        case .kwai2: return .kwai2
        case .kwai3: return .kwai3
        case .kwai4: return .kwai4
        case .kwai5: return .kwai5
        case .kwan1: return .kwan1
        case .kwan2: return .kwan2
        case .kwan3: return .kwan3
        case .kwan4: return .kwan4
        case .kwan5: return .kwan5
        case .kwang1: return .kwang1
        case .kwang3: return .kwang3
        case .kwik1: return .kwik1
        case .kwok3: return .kwok3
        case .kwong1: return .kwong1
        case .kwong2: return .kwong2
        case .kwong3: return .kwong3
        case .kwong4: return .kwong4
        case .kwu1: return .kwu1
        case .kwui2: return .kwui2
        case .kwui3: return .kwui3
        case .kwut3: return .kwut3
        case .kyun2: return .kyun2
        case .kyun4: return .kyun4
        case .kyut3: return .kyut3
        case .kyut6: return .kyut6
        case .laa1: return .laa1
        case .laa2: return .laa2
        case .laa3: return .laa3
        case .laa4: return .laa4
        case .laa5: return .laa5
        case .laa6: return .laa6
        case .laai1: return .laai1
        case .laai2: return .laai2
        case .laai3: return .laai3
        case .laai4: return .laai4
        case .laai5: return .laai5
        case .laai6: return .laai6
        case .laak1: return .laak1
        case .laak3: return .laak3
        case .laak6: return .laak6
        case .laam2: return .laam2
        case .laam3: return .laam3
        case .laam4: return .laam4
        case .laam5: return .laam5
        case .laam6: return .laam6
        case .laan1: return .laan1
        case .laan2: return .laan2
        case .laan4: return .laan4
        case .laan5: return .laan5
        case .laan6: return .laan6
        case .laang1: return .laang1
        case .laang4: return .laang4
        case .laang5: return .laang5
        case .laang6: return .laang6
        case .laap2: return .laap2
        case .laap3: return .laap3
        case .laap6: return .laap6
        case .laat1: return .laat1
        case .laat2: return .laat2
        case .laat3: return .laat3
        case .laat6: return .laat6
        case .laau1: return .laau1
        case .laau2: return .laau2
        case .laau4: return .laau4
        case .laau5: return .laau5
        case .laau6: return .laau6
        case .lai2: return .lai2
        case .lai4: return .lai4
        case .lai5: return .lai5
        case .lai6: return .lai6
        case .lak6: return .lak6
        case .lam1: return .lam1
        case .lam2: return .lam2
        case .lam3: return .lam3
        case .lam4: return .lam4
        case .lam5: return .lam5
        case .lam6: return .lam6
        case .lan2: return .lan2
        case .lan4: return .lan4
        case .lang1: return .lang1
        case .lang3: return .lang3
        case .lang4: return .lang4
        case .lang6: return .lang6
        case .lap1: return .lap1
        case .lap2: return .lap2
        case .lap6: return .lap6
        case .lat1: return .lat1
        case .lat6: return .lat6
        case .lau1: return .lau1
        case .lau2: return .lau2
        case .lau3: return .lau3
        case .lau4: return .lau4
        case .lau5: return .lau5
        case .lau6: return .lau6
        case .le1: return .le1
        case .le2: return .le2
        case .le3: return .le3
        case .le4: return .le4
        case .le5: return .le5
        case .le6: return .le6
        case .lei1: return .lei1
        case .lei2: return .lei2
        case .lei4: return .lei4
        case .lei5: return .lei5
        case .lei6: return .lei6
        case .lek1: return .lek1
        case .lek6: return .lek6
        case .lem2: return .lem2
        case .leng1: return .leng1
        case .leng2: return .leng2
        case .leng3: return .leng3
        case .leng4: return .leng4
        case .leng5: return .leng5
        case .leoi1: return .leoi1
        case .leoi2: return .leoi2
        case .leoi3: return .leoi3
        case .leoi4: return .leoi4
        case .leoi5: return .leoi5
        case .leoi6: return .leoi6
        case .leon1: return .leon1
        case .leon2: return .leon2
        case .leon4: return .leon4
        case .leon5: return .leon5
        case .leon6: return .leon6
        case .leot2: return .leot2
        case .leot3: return .leot3
        case .leot6: return .leot6
        case .li1: return .li1
        case .li2: return .li2
        case .li4: return .li4
        case .lik1: return .lik1
        case .lik6: return .lik6
        case .lim1: return .lim1
        case .lim2: return .lim2
        case .lim3: return .lim3
        case .lim4: return .lim4
        case .lim5: return .lim5
        case .lim6: return .lim6
        case .lin1: return .lin1
        case .lin2: return .lin2
        case .lin4: return .lin4
        case .lin5: return .lin5
        case .lin6: return .lin6
        case .ling1: return .ling1
        case .ling2: return .ling2
        case .ling3: return .ling3
        case .ling4: return .ling4
        case .ling5: return .ling5
        case .ling6: return .ling6
        case .lip1: return .lip1
        case .lip6: return .lip6
        case .lit3: return .lit3
        case .lit6: return .lit6
        case .liu1: return .liu1
        case .liu2: return .liu2
        case .liu4: return .liu4
        case .liu5: return .liu5
        case .liu6: return .liu6
        case .lo1: return .lo1
        case .lo2: return .lo2
        case .lo3: return .lo3
        case .lo4: return .lo4
        case .lo5: return .lo5
        case .lo6: return .lo6
        case .loe1: return .loe1
        case .loe2: return .loe2
        case .loek1: return .loek1
        case .loek2: return .loek2
        case .loek6: return .loek6
        case .loeng2: return .loeng2
        case .loeng4: return .loeng4
        case .loeng5: return .loeng5
        case .loeng6: return .loeng6
        case .loi1: return .loi1
        case .loi2: return .loi2
        case .loi4: return .loi4
        case .loi5: return .loi5
        case .loi6: return .loi6
        case .lok1: return .lok1
        case .lok2: return .lok2
        case .lok3: return .lok3
        case .lok6: return .lok6
        case .long1: return .long1
        case .long2: return .long2
        case .long3: return .long3
        case .long4: return .long4
        case .long5: return .long5
        case .long6: return .long6
        case .lou1: return .lou1
        case .lou2: return .lou2
        case .lou4: return .lou4
        case .lou5: return .lou5
        case .lou6: return .lou6
        case .lu1: return .lu1
        case .luk1: return .luk1
        case .luk2: return .luk2
        case .luk6: return .luk6
        case .lung1: return .lung1
        case .lung2: return .lung2
        case .lung4: return .lung4
        case .lung5: return .lung5
        case .lung6: return .lung6
        case .lyun1: return .lyun1
        case .lyun2: return .lyun2
        case .lyun4: return .lyun4
        case .lyun5: return .lyun5
        case .lyun6: return .lyun6
        case .lyut1: return .lyut1
        case .lyut3: return .lyut3
        case .lyut6: return .lyut6
        case .m2: return .m2
        case .m4: return .m4
        case .m5: return .m5
        case .m6: return .m6
        case .maa1: return .maa1
        case .maa2: return .maa2
        case .maa3: return .maa3
        case .maa4: return .maa4
        case .maa5: return .maa5
        case .maa6: return .maa6
        case .maai2: return .maai2
        case .maai4: return .maai4
        case .maai5: return .maai5
        case .maai6: return .maai6
        case .maak1: return .maak1
        case .maak3: return .maak3
        case .maak6: return .maak6
        case .maan1: return .maan1
        case .maan2: return .maan2
        case .maan4: return .maan4
        case .maan5: return .maan5
        case .maan6: return .maan6
        case .maang1: return .maang1
        case .maang2: return .maang2
        case .maang4: return .maang4
        case .maang5: return .maang5
        case .maang6: return .maang6
        case .maat3: return .maat3
        case .maat6: return .maat6
        case .maau1: return .maau1
        case .maau4: return .maau4
        case .maau5: return .maau5
        case .maau6: return .maau6
        case .mai1: return .mai1
        case .mai2: return .mai2
        case .mai4: return .mai4
        case .mai5: return .mai5
        case .mai6: return .mai6
        case .mak1: return .mak1
        case .mak2: return .mak2
        case .mak6: return .mak6
        case .mam1: return .mam1
        case .man1: return .man1
        case .man2: return .man2
        case .man3: return .man3
        case .man4: return .man4
        case .man5: return .man5
        case .man6: return .man6
        case .mang1: return .mang1
        case .mang2: return .mang2
        case .mang3: return .mang3
        case .mang4: return .mang4
        case .mang6: return .mang6
        case .mat1: return .mat1
        case .mat2: return .mat2
        case .mat6: return .mat6
        case .mau1: return .mau1
        case .mau4: return .mau4
        case .mau5: return .mau5
        case .mau6: return .mau6
        case .me1: return .me1
        case .me2: return .me2
        case .me5: return .me5
        case .me6: return .me6
        case .mei1: return .mei1
        case .mei2: return .mei2
        case .mei4: return .mei4
        case .mei5: return .mei5
        case .mei6: return .mei6
        case .men1: return .men1
        case .meng2: return .meng2
        case .meng4: return .meng4
        case .meng6: return .meng6
        case .mi1: return .mi1
        case .mi4: return .mi4
        case .mik6: return .mik6
        case .min1: return .min1
        case .min2: return .min2
        case .min4: return .min4
        case .min5: return .min5
        case .min6: return .min6
        case .ming1: return .ming1
        case .ming2: return .ming2
        case .ming4: return .ming4
        case .ming5: return .ming5
        case .ming6: return .ming6
        case .mit1: return .mit1
        case .mit6: return .mit6
        case .miu1: return .miu1
        case .miu2: return .miu2
        case .miu4: return .miu4
        case .miu5: return .miu5
        case .miu6: return .miu6
        case .mo1: return .mo1
        case .mo2: return .mo2
        case .mo4: return .mo4
        case .mo5: return .mo5
        case .mo6: return .mo6
        case .mok1: return .mok1
        case .mok2: return .mok2
        case .mok6: return .mok6
        case .mong1: return .mong1
        case .mong2: return .mong2
        case .mong4: return .mong4
        case .mong5: return .mong5
        case .mong6: return .mong6
        case .mou1: return .mou1
        case .mou2: return .mou2
        case .mou4: return .mou4
        case .mou5: return .mou5
        case .mou6: return .mou6
        case .mui1: return .mui1
        case .mui2: return .mui2
        case .mui4: return .mui4
        case .mui5: return .mui5
        case .mui6: return .mui6
        case .muk1: return .muk1
        case .muk6: return .muk6
        case .mun1: return .mun1
        case .mun2: return .mun2
        case .mun4: return .mun4
        case .mun5: return .mun5
        case .mun6: return .mun6
        case .mung1: return .mung1
        case .mung2: return .mung2
        case .mung4: return .mung4
        case .mung5: return .mung5
        case .mung6: return .mung6
        case .mut1: return .mut1
        case .mut2: return .mut2
        case .mut3: return .mut3
        case .mut6: return .mut6
        case .naa1: return .naa1
        case .naa2: return .naa2
        case .naa3: return .naa3
        case .naa4: return .naa4
        case .naa5: return .naa5
        case .naa6: return .naa6
        case .naai1: return .naai1
        case .naai2: return .naai2
        case .naai3: return .naai3
        case .naai4: return .naai4
        case .naai5: return .naai5
        case .naai6: return .naai6
        case .naam2: return .naam2
        case .naam3: return .naam3
        case .naam4: return .naam4
        case .naam5: return .naam5
        case .naam6: return .naam6
        case .naan2: return .naan2
        case .naan3: return .naan3
        case .naan4: return .naan4
        case .naan5: return .naan5
        case .naan6: return .naan6
        case .naap2: return .naap2
        case .naap6: return .naap6
        case .naat3: return .naat3
        case .naat6: return .naat6
        case .naau1: return .naau1
        case .naau2: return .naau2
        case .naau4: return .naau4
        case .naau5: return .naau5
        case .naau6: return .naau6
        case .nai2: return .nai2
        case .nai4: return .nai4
        case .nai5: return .nai5
        case .nai6: return .nai6
        case .nak1: return .nak1
        case .nak6: return .nak6
        case .nam2: return .nam2
        case .nam4: return .nam4
        case .nam5: return .nam5
        case .nam6: return .nam6
        case .nan2: return .nan2
        case .nan4: return .nan4
        case .nang3: return .nang3
        case .nang4: return .nang4
        case .nap1: return .nap1
        case .nap6: return .nap6
        case .nat6: return .nat6
        case .nau1: return .nau1
        case .nau2: return .nau2
        case .nau4: return .nau4
        case .nau5: return .nau5
        case .nau6: return .nau6
        case .ne1: return .ne1
        case .ne6: return .ne6
        case .nei1: return .nei1
        case .nei2: return .nei2
        case .nei4: return .nei4
        case .nei5: return .nei5
        case .nei6: return .nei6
        case .neoi2: return .neoi2
        case .neoi4: return .neoi4
        case .neoi5: return .neoi5
        case .neoi6: return .neoi6
        case .neot6: return .neot6
        case .ng2: return .ng2
        case .ng4: return .ng4
        case .ng5: return .ng5
        case .ng6: return .ng6
        case .ngaa1: return .ngaa1
        case .ngaa2: return .ngaa2
        case .ngaa3: return .ngaa3
        case .ngaa4: return .ngaa4
        case .ngaa5: return .ngaa5
        case .ngaa6: return .ngaa6
        case .ngaai1: return .ngaai1
        case .ngaai2: return .ngaai2
        case .ngaai3: return .ngaai3
        case .ngaai4: return .ngaai4
        case .ngaai5: return .ngaai5
        case .ngaai6: return .ngaai6
        case .ngaak1: return .ngaak1
        case .ngaak2: return .ngaak2
        case .ngaak3: return .ngaak3
        case .ngaak6: return .ngaak6
        case .ngaam1: return .ngaam1
        case .ngaam4: return .ngaam4
        case .ngaan2: return .ngaan2
        case .ngaan3: return .ngaan3
        case .ngaan4: return .ngaan4
        case .ngaan5: return .ngaan5
        case .ngaan6: return .ngaan6
        case .ngaang1: return .ngaang1
        case .ngaang2: return .ngaang2
        case .ngaang6: return .ngaang6
        case .ngaap2: return .ngaap2
        case .ngaap3: return .ngaap3
        case .ngaat1: return .ngaat1
        case .ngaat2: return .ngaat2
        case .ngaat3: return .ngaat3
        case .ngaat6: return .ngaat6
        case .ngaau1: return .ngaau1
        case .ngaau2: return .ngaau2
        case .ngaau3: return .ngaau3
        case .ngaau4: return .ngaau4
        case .ngaau5: return .ngaau5
        case .ngaau6: return .ngaau6
        case .ngai1: return .ngai1
        case .ngai2: return .ngai2
        case .ngai3: return .ngai3
        case .ngai4: return .ngai4
        case .ngai5: return .ngai5
        case .ngai6: return .ngai6
        case .ngak1: return .ngak1
        case .ngam1: return .ngam1
        case .ngam2: return .ngam2
        case .ngam3: return .ngam3
        case .ngam4: return .ngam4
        case .ngam5: return .ngam5
        case .ngam6: return .ngam6
        case .ngan1: return .ngan1
        case .ngan2: return .ngan2
        case .ngan3: return .ngan3
        case .ngan4: return .ngan4
        case .ngan6: return .ngan6
        case .ngang1: return .ngang1
        case .ngang2: return .ngang2
        case .ngang3: return .ngang3
        case .ngap1: return .ngap1
        case .ngap6: return .ngap6
        case .ngat1: return .ngat1
        case .ngat6: return .ngat6
        case .ngau1: return .ngau1
        case .ngau2: return .ngau2
        case .ngau3: return .ngau3
        case .ngau4: return .ngau4
        case .ngau5: return .ngau5
        case .ngau6: return .ngau6
        case .nge4: return .nge4
        case .nge6: return .nge6
        case .ngei1: return .ngei1
        case .ngei3: return .ngei3
        case .ngei6: return .ngei6
        case .ngi1: return .ngi1
        case .ngit6: return .ngit6
        case .ngm2: return .ngm2
        case .ngm4: return .ngm4
        case .ngm6: return .ngm6
        case .ngo1: return .ngo1
        case .ngo2: return .ngo2
        case .ngo4: return .ngo4
        case .ngo5: return .ngo5
        case .ngo6: return .ngo6
        case .ngoi1: return .ngoi1
        case .ngoi2: return .ngoi2
        case .ngoi3: return .ngoi3
        case .ngoi4: return .ngoi4
        case .ngoi6: return .ngoi6
        case .ngok2: return .ngok2
        case .ngok3: return .ngok3
        case .ngok6: return .ngok6
        case .ngon1: return .ngon1
        case .ngon2: return .ngon2
        case .ngon3: return .ngon3
        case .ngon4: return .ngon4
        case .ngon6: return .ngon6
        case .ngong1: return .ngong1
        case .ngong2: return .ngong2
        case .ngong3: return .ngong3
        case .ngong4: return .ngong4
        case .ngong5: return .ngong5
        case .ngong6: return .ngong6
        case .ngot6: return .ngot6
        case .ngou1: return .ngou1
        case .ngou2: return .ngou2
        case .ngou3: return .ngou3
        case .ngou4: return .ngou4
        case .ngou6: return .ngou6
        case .nguk1: return .nguk1
        case .ngung1: return .ngung1
        case .ngung2: return .ngung2
        case .ngung3: return .ngung3
        case .ni1: return .ni1
        case .nik1: return .nik1
        case .nik6: return .nik6
        case .nim1: return .nim1
        case .nim2: return .nim2
        case .nim3: return .nim3
        case .nim4: return .nim4
        case .nim5: return .nim5
        case .nim6: return .nim6
        case .nin1: return .nin1
        case .nin2: return .nin2
        case .nin4: return .nin4
        case .nin5: return .nin5
        case .nin6: return .nin6
        case .ning1: return .ning1
        case .ning2: return .ning2
        case .ning4: return .ning4
        case .ning5: return .ning5
        case .ning6: return .ning6
        case .nip1: return .nip1
        case .nip6: return .nip6
        case .nit6: return .nit6
        case .niu1: return .niu1
        case .niu2: return .niu2
        case .niu5: return .niu5
        case .niu6: return .niu6
        case .no1: return .no1
        case .no2: return .no2
        case .no4: return .no4
        case .no5: return .no5
        case .no6: return .no6
        case .noek6: return .noek6
        case .noeng2: return .noeng2
        case .noeng4: return .noeng4
        case .noeng6: return .noeng6
        case .noi1: return .noi1
        case .noi2: return .noi2
        case .noi4: return .noi4
        case .noi5: return .noi5
        case .noi6: return .noi6
        case .nok6: return .nok6
        case .nong1: return .nong1
        case .nong2: return .nong2
        case .nong4: return .nong4
        case .nong5: return .nong5
        case .nong6: return .nong6
        case .nou4: return .nou4
        case .nou5: return .nou5
        case .nou6: return .nou6
        case .nuk6: return .nuk6
        case .nung1: return .nung1
        case .nung4: return .nung4
        case .nung5: return .nung5
        case .nung6: return .nung6
        case .nyun2: return .nyun2
        case .nyun4: return .nyun4
        case .nyun5: return .nyun5
        case .nyun6: return .nyun6
        case .o1: return .o1
        case .o2: return .o2
        case .o4: return .o4
        case .o5: return .o5
        case .o6: return .o6
        case .oi1: return .oi1
        case .oi2: return .oi2
        case .oi3: return .oi3
        case .oi4: return .oi4
        case .oi6: return .oi6
        case .ok2: return .ok2
        case .ok3: return .ok3
        case .ok6: return .ok6
        case .on1: return .on1
        case .on2: return .on2
        case .on3: return .on3
        case .on4: return .on4
        case .on6: return .on6
        case .ong1: return .ong1
        case .ong2: return .ong2
        case .ong3: return .ong3
        case .ong4: return .ong4
        case .ong5: return .ong5
        case .ong6: return .ong6
        case .ot6: return .ot6
        case .ou1: return .ou1
        case .ou2: return .ou2
        case .ou3: return .ou3
        case .ou4: return .ou4
        case .ou6: return .ou6
        case .paa1: return .paa1
        case .paa2: return .paa2
        case .paa3: return .paa3
        case .paa4: return .paa4
        case .paai1: return .paai1
        case .paai2: return .paai2
        case .paai3: return .paai3
        case .paai4: return .paai4
        case .paak1: return .paak1
        case .paak2: return .paak2
        case .paak3: return .paak3
        case .paak4: return .paak4
        case .paak6: return .paak6
        case .paan1: return .paan1
        case .paan3: return .paan3
        case .paang1: return .paang1
        case .paang2: return .paang2
        case .paang4: return .paang4
        case .paang5: return .paang5
        case .paang6: return .paang6
        case .paat1: return .paat1
        case .paat3: return .paat3
        case .paat6: return .paat6
        case .paau1: return .paau1
        case .paau2: return .paau2
        case .paau3: return .paau3
        case .paau4: return .paau4
        case .pai1: return .pai1
        case .pai2: return .pai2
        case .pai3: return .pai3
        case .pai5: return .pai5
        case .pai6: return .pai6
        case .pan1: return .pan1
        case .pan3: return .pan3
        case .pan4: return .pan4
        case .pan5: return .pan5
        case .pang2: return .pang2
        case .pang3: return .pang3
        case .pang4: return .pang4
        case .pat1: return .pat1
        case .pat6: return .pat6
        case .pau1: return .pau1
        case .pau2: return .pau2
        case .pau3: return .pau3
        case .pau4: return .pau4
        case .pe1: return .pe1
        case .pe5: return .pe5
        case .pei1: return .pei1
        case .pei2: return .pei2
        case .pei3: return .pei3
        case .pei4: return .pei4
        case .pei5: return .pei5
        case .pei6: return .pei6
        case .pek1: return .pek1
        case .pek3: return .pek3
        case .pek6: return .pek6
        case .pen1: return .pen1
        case .peng1: return .peng1
        case .peng2: return .peng2
        case .peng4: return .peng4
        case .pet1: return .pet1
        case .pet6: return .pet6
        case .pi1: return .pi1
        case .pik1: return .pik1
        case .pin1: return .pin1
        case .pin2: return .pin2
        case .pin3: return .pin3
        case .pin4: return .pin4
        case .pin5: return .pin5
        case .ping1: return .ping1
        case .ping2: return .ping2
        case .ping3: return .ping3
        case .ping4: return .ping4
        case .pit3: return .pit3
        case .piu1: return .piu1
        case .piu2: return .piu2
        case .piu3: return .piu3
        case .piu4: return .piu4
        case .piu5: return .piu5
        case .po1: return .po1
        case .po2: return .po2
        case .po3: return .po3
        case .po4: return .po4
        case .pok1: return .pok1
        case .pok2: return .pok2
        case .pok3: return .pok3
        case .pong1: return .pong1
        case .pong2: return .pong2
        case .pong3: return .pong3
        case .pong4: return .pong4
        case .pong5: return .pong5
        case .pot1: return .pot1
        case .pou1: return .pou1
        case .pou2: return .pou2
        case .pou3: return .pou3
        case .pou4: return .pou4
        case .pou5: return .pou5
        case .pou6: return .pou6
        case .pui1: return .pui1
        case .pui2: return .pui2
        case .pui3: return .pui3
        case .pui4: return .pui4
        case .pui5: return .pui5
        case .pui6: return .pui6
        case .puk1: return .puk1
        case .puk3: return .puk3
        case .puk6: return .puk6
        case .pun1: return .pun1
        case .pun2: return .pun2
        case .pun3: return .pun3
        case .pun4: return .pun4
        case .pun5: return .pun5
        case .pun6: return .pun6
        case .pung1: return .pung1
        case .pung2: return .pung2
        case .pung3: return .pung3
        case .pung4: return .pung4
        case .put3: return .put3
        case .put6: return .put6
        case .saa1: return .saa1
        case .saa2: return .saa2
        case .saa3: return .saa3
        case .saa4: return .saa4
        case .saai1: return .saai1
        case .saai2: return .saai2
        case .saai3: return .saai3
        case .saai4: return .saai4
        case .saai5: return .saai5
        case .saak3: return .saak3
        case .saam1: return .saam1
        case .saam2: return .saam2
        case .saam3: return .saam3
        case .saam4: return .saam4
        case .saan1: return .saan1
        case .saan2: return .saan2
        case .saan3: return .saan3
        case .saan4: return .saan4
        case .saang1: return .saang1
        case .saang2: return .saang2
        case .saap1: return .saap1
        case .saap3: return .saap3
        case .saap6: return .saap6
        case .saat2: return .saat2
        case .saat3: return .saat3
        case .saau1: return .saau1
        case .saau2: return .saau2
        case .saau3: return .saau3
        case .saau4: return .saau4
        case .sai1: return .sai1
        case .sai2: return .sai2
        case .sai3: return .sai3
        case .sai4: return .sai4
        case .sai6: return .sai6
        case .sak1: return .sak1
        case .sam1: return .sam1
        case .sam2: return .sam2
        case .sam3: return .sam3
        case .sam4: return .sam4
        case .sam6: return .sam6
        case .san1: return .san1
        case .san2: return .san2
        case .san3: return .san3
        case .san4: return .san4
        case .san5: return .san5
        case .san6: return .san6
        case .sang1: return .sang1
        case .sang3: return .sang3
        case .sap1: return .sap1
        case .sap6: return .sap6
        case .sat1: return .sat1
        case .sat6: return .sat6
        case .sau1: return .sau1
        case .sau2: return .sau2
        case .sau3: return .sau3
        case .sau4: return .sau4
        case .sau6: return .sau6
        case .se1: return .se1
        case .se2: return .se2
        case .se3: return .se3
        case .se4: return .se4
        case .se5: return .se5
        case .se6: return .se6
        case .sei2: return .sei2
        case .sei3: return .sei3
        case .sek2: return .sek2
        case .sek3: return .sek3
        case .sek6: return .sek6
        case .sen1: return .sen1
        case .seng1: return .seng1
        case .seng2: return .seng2
        case .seng3: return .seng3
        case .seng4: return .seng4
        case .seoi1: return .seoi1
        case .seoi2: return .seoi2
        case .seoi3: return .seoi3
        case .seoi4: return .seoi4
        case .seoi5: return .seoi5
        case .seoi6: return .seoi6
        case .seon1: return .seon1
        case .seon2: return .seon2
        case .seon3: return .seon3
        case .seon4: return .seon4
        case .seon5: return .seon5
        case .seon6: return .seon6
        case .seot1: return .seot1
        case .seot2: return .seot2
        case .seot6: return .seot6
        case .set1: return .set1
        case .seu1: return .seu1
        case .si1: return .si1
        case .si2: return .si2
        case .si3: return .si3
        case .si4: return .si4
        case .si5: return .si5
        case .si6: return .si6
        case .sik1: return .sik1
        case .sik2: return .sik2
        case .sik3: return .sik3
        case .sik6: return .sik6
        case .sim1: return .sim1
        case .sim2: return .sim2
        case .sim3: return .sim3
        case .sim4: return .sim4
        case .sim6: return .sim6
        case .sin1: return .sin1
        case .sin2: return .sin2
        case .sin3: return .sin3
        case .sin4: return .sin4
        case .sin5: return .sin5
        case .sin6: return .sin6
        case .sing1: return .sing1
        case .sing2: return .sing2
        case .sing3: return .sing3
        case .sing4: return .sing4
        case .sing6: return .sing6
        case .sip3: return .sip3
        case .sit3: return .sit3
        case .sit6: return .sit6
        case .siu1: return .siu1
        case .siu2: return .siu2
        case .siu3: return .siu3
        case .siu4: return .siu4
        case .siu6: return .siu6
        case .so1: return .so1
        case .so2: return .so2
        case .so3: return .so3
        case .so4: return .so4
        case .soe4: return .soe4
        case .soek3: return .soek3
        case .soeng1: return .soeng1
        case .soeng2: return .soeng2
        case .soeng3: return .soeng3
        case .soeng4: return .soeng4
        case .soeng5: return .soeng5
        case .soeng6: return .soeng6
        case .soi1: return .soi1
        case .soi2: return .soi2
        case .sok1: return .sok1
        case .sok3: return .sok3
        case .song1: return .song1
        case .song2: return .song2
        case .song3: return .song3
        case .sot1: return .sot1
        case .sou1: return .sou1
        case .sou2: return .sou2
        case .sou3: return .sou3
        case .sou4: return .sou4
        case .su4: return .su4
        case .suk1: return .suk1
        case .suk3: return .suk3
        case .suk6: return .suk6
        case .sung1: return .sung1
        case .sung2: return .sung2
        case .sung3: return .sung3
        case .sung4: return .sung4
        case .syu1: return .syu1
        case .syu2: return .syu2
        case .syu3: return .syu3
        case .syu4: return .syu4
        case .syu5: return .syu5
        case .syu6: return .syu6
        case .syun1: return .syun1
        case .syun2: return .syun2
        case .syun3: return .syun3
        case .syun4: return .syun4
        case .syun5: return .syun5
        case .syun6: return .syun6
        case .syut1: return .syut1
        case .syut3: return .syut3
        case .taa1: return .taa1
        case .taai1: return .taai1
        case .taai2: return .taai2
        case .taai3: return .taai3
        case .taai5: return .taai5
        case .taam1: return .taam1
        case .taam2: return .taam2
        case .taam3: return .taam3
        case .taam4: return .taam4
        case .taam5: return .taam5
        case .taan1: return .taan1
        case .taan2: return .taan2
        case .taan3: return .taan3
        case .taan4: return .taan4
        case .taap1: return .taap1
        case .taap2: return .taap2
        case .taap3: return .taap3
        case .taat1: return .taat1
        case .taat3: return .taat3
        case .taat6: return .taat6
        case .tai1: return .tai1
        case .tai2: return .tai2
        case .tai3: return .tai3
        case .tai4: return .tai4
        case .tai5: return .tai5
        case .tam2: return .tam2
        case .tam3: return .tam3
        case .tam4: return .tam4
        case .tam5: return .tam5
        case .tan1: return .tan1
        case .tan2: return .tan2
        case .tan3: return .tan3
        case .tan4: return .tan4
        case .tang1: return .tang1
        case .tang3: return .tang3
        case .tang4: return .tang4
        case .tap1: return .tap1
        case .tau1: return .tau1
        case .tau2: return .tau2
        case .tau3: return .tau3
        case .tau4: return .tau4
        case .tek3: return .tek3
        case .teng1: return .teng1
        case .teng5: return .teng5
        case .teoi1: return .teoi1
        case .teoi2: return .teoi2
        case .teoi3: return .teoi3
        case .teoi4: return .teoi4
        case .teon1: return .teon1
        case .teon2: return .teon2
        case .teon3: return .teon3
        case .teon5: return .teon5
        case .teot1: return .teot1
        case .teu4: return .teu4
        case .ti1: return .ti1
        case .ti4: return .ti4
        case .tik1: return .tik1
        case .tim1: return .tim1
        case .tim2: return .tim2
        case .tim3: return .tim3
        case .tim4: return .tim4
        case .tim5: return .tim5
        case .tin1: return .tin1
        case .tin2: return .tin2
        case .tin3: return .tin3
        case .tin4: return .tin4
        case .tin5: return .tin5
        case .ting1: return .ting1
        case .ting2: return .ting2
        case .ting3: return .ting3
        case .ting4: return .ting4
        case .ting5: return .ting5
        case .ting6: return .ting6
        case .tip1: return .tip1
        case .tip2: return .tip2
        case .tip3: return .tip3
        case .tit3: return .tit3
        case .tiu1: return .tiu1
        case .tiu2: return .tiu2
        case .tiu3: return .tiu3
        case .tiu4: return .tiu4
        case .tiu5: return .tiu5
        case .to1: return .to1
        case .to2: return .to2
        case .to3: return .to3
        case .to4: return .to4
        case .to5: return .to5
        case .toe3: return .toe3
        case .toe5: return .toe5
        case .toi1: return .toi1
        case .toi2: return .toi2
        case .toi4: return .toi4
        case .toi5: return .toi5
        case .tok1: return .tok1
        case .tok2: return .tok2
        case .tok3: return .tok3
        case .tong1: return .tong1
        case .tong2: return .tong2
        case .tong3: return .tong3
        case .tong4: return .tong4
        case .tong5: return .tong5
        case .tou1: return .tou1
        case .tou2: return .tou2
        case .tou3: return .tou3
        case .tou4: return .tou4
        case .tou5: return .tou5
        case .tuk1: return .tuk1
        case .tung1: return .tung1
        case .tung2: return .tung2
        case .tung3: return .tung3
        case .tung4: return .tung4
        case .tyun1: return .tyun1
        case .tyun2: return .tyun2
        case .tyun4: return .tyun4
        case .tyun5: return .tyun5
        case .tyut1: return .tyut1
        case .tyut3: return .tyut3
        case .uk1: return .uk1
        case .ung1: return .ung1
        case .ung2: return .ung2
        case .ung3: return .ung3
        case .waa1: return .waa1
        case .waa2: return .waa2
        case .waa4: return .waa4
        case .waa5: return .waa5
        case .waa6: return .waa6
        case .waai1: return .waai1
        case .waai2: return .waai2
        case .waai4: return .waai4
        case .waai6: return .waai6
        case .waak1: return .waak1
        case .waak2: return .waak2
        case .waak6: return .waak6
        case .waan1: return .waan1
        case .waan2: return .waan2
        case .waan4: return .waan4
        case .waan5: return .waan5
        case .waan6: return .waan6
        case .waang1: return .waang1
        case .waang4: return .waang4
        case .waang6: return .waang6
        case .waat2: return .waat2
        case .waat3: return .waat3
        case .waat6: return .waat6
        case .wai1: return .wai1
        case .wai2: return .wai2
        case .wai3: return .wai3
        case .wai4: return .wai4
        case .wai5: return .wai5
        case .wai6: return .wai6
        case .wak6: return .wak6
        case .wan1: return .wan1
        case .wan2: return .wan2
        case .wan3: return .wan3
        case .wan4: return .wan4
        case .wan5: return .wan5
        case .wan6: return .wan6
        case .wang2: return .wang2
        case .wang4: return .wang4
        case .wang6: return .wang6
        case .wat1: return .wat1
        case .wat2: return .wat2
        case .wat6: return .wat6
        case .we2: return .we2
        case .we5: return .we5
        case .wen1: return .wen1
        case .wet1: return .wet1
        case .wi1: return .wi1
        case .wik6: return .wik6
        case .wing1: return .wing1
        case .wing4: return .wing4
        case .wing5: return .wing5
        case .wing6: return .wing6
        case .wo1: return .wo1
        case .wo2: return .wo2
        case .wo3: return .wo3
        case .wo4: return .wo4
        case .wo5: return .wo5
        case .wo6: return .wo6
        case .woek1: return .woek1
        case .wok1: return .wok1
        case .wok2: return .wok2
        case .wok3: return .wok3
        case .wok6: return .wok6
        case .wong1: return .wong1
        case .wong2: return .wong2
        case .wong4: return .wong4
        case .wong5: return .wong5
        case .wong6: return .wong6
        case .wu1: return .wu1
        case .wu2: return .wu2
        case .wu3: return .wu3
        case .wu4: return .wu4
        case .wu6: return .wu6
        case .wui1: return .wui1
        case .wui2: return .wui2
        case .wui3: return .wui3
        case .wui4: return .wui4
        case .wui5: return .wui5
        case .wui6: return .wui6
        case .wun1: return .wun1
        case .wun2: return .wun2
        case .wun3: return .wun3
        case .wun4: return .wun4
        case .wun5: return .wun5
        case .wun6: return .wun6
        case .wut6: return .wut6
        case .zaa1: return .zaa1
        case .zaa2: return .zaa2
        case .zaa3: return .zaa3
        case .zaa6: return .zaa6
        case .zaai1: return .zaai1
        case .zaai2: return .zaai2
        case .zaai3: return .zaai3
        case .zaai6: return .zaai6
        case .zaak2: return .zaak2
        case .zaak3: return .zaak3
        case .zaak6: return .zaak6
        case .zaam1: return .zaam1
        case .zaam2: return .zaam2
        case .zaam3: return .zaam3
        case .zaam6: return .zaam6
        case .zaan1: return .zaan1
        case .zaan2: return .zaan2
        case .zaan3: return .zaan3
        case .zaan6: return .zaan6
        case .zaang1: return .zaang1
        case .zaang3: return .zaang3
        case .zaang6: return .zaang6
        case .zaap2: return .zaap2
        case .zaap3: return .zaap3
        case .zaap6: return .zaap6
        case .zaat2: return .zaat2
        case .zaat3: return .zaat3
        case .zaat6: return .zaat6
        case .zaau1: return .zaau1
        case .zaau2: return .zaau2
        case .zaau3: return .zaau3
        case .zaau6: return .zaau6
        case .zai1: return .zai1
        case .zai2: return .zai2
        case .zai3: return .zai3
        case .zai4: return .zai4
        case .zai6: return .zai6
        case .zak1: return .zak1
        case .zam1: return .zam1
        case .zam2: return .zam2
        case .zam3: return .zam3
        case .zam4: return .zam4
        case .zam6: return .zam6
        case .zan1: return .zan1
        case .zan2: return .zan2
        case .zan3: return .zan3
        case .zan5: return .zan5
        case .zan6: return .zan6
        case .zang1: return .zang1
        case .zang2: return .zang2
        case .zang3: return .zang3
        case .zang6: return .zang6
        case .zap1: return .zap1
        case .zap6: return .zap6
        case .zat1: return .zat1
        case .zat2: return .zat2
        case .zat6: return .zat6
        case .zau1: return .zau1
        case .zau2: return .zau2
        case .zau3: return .zau3
        case .zau6: return .zau6
        case .ze1: return .ze1
        case .ze2: return .ze2
        case .ze3: return .ze3
        case .ze4: return .ze4
        case .ze5: return .ze5
        case .ze6: return .ze6
        case .zek1: return .zek1
        case .zek3: return .zek3
        case .zek6: return .zek6
        case .zem1: return .zem1
        case .zeng1: return .zeng1
        case .zeng2: return .zeng2
        case .zeng3: return .zeng3
        case .zeng6: return .zeng6
        case .zeoi1: return .zeoi1
        case .zeoi2: return .zeoi2
        case .zeoi3: return .zeoi3
        case .zeoi6: return .zeoi6
        case .zeon1: return .zeon1
        case .zeon2: return .zeon2
        case .zeon3: return .zeon3
        case .zeon6: return .zeon6
        case .zeot1: return .zeot1
        case .zeot6: return .zeot6
        case .zep6: return .zep6
        case .zi1: return .zi1
        case .zi2: return .zi2
        case .zi3: return .zi3
        case .zi4: return .zi4
        case .zi6: return .zi6
        case .zik1: return .zik1
        case .zik2: return .zik2
        case .zik3: return .zik3
        case .zik6: return .zik6
        case .zim1: return .zim1
        case .zim2: return .zim2
        case .zim3: return .zim3
        case .zim6: return .zim6
        case .zin1: return .zin1
        case .zin2: return .zin2
        case .zin3: return .zin3
        case .zin6: return .zin6
        case .zing1: return .zing1
        case .zing2: return .zing2
        case .zing3: return .zing3
        case .zing6: return .zing6
        case .zip1: return .zip1
        case .zip2: return .zip2
        case .zip3: return .zip3
        case .zip6: return .zip6
        case .zit1: return .zit1
        case .zit2: return .zit2
        case .zit3: return .zit3
        case .zit6: return .zit6
        case .ziu1: return .ziu1
        case .ziu2: return .ziu2
        case .ziu3: return .ziu3
        case .ziu6: return .ziu6
        case .zo2: return .zo2
        case .zo3: return .zo3
        case .zo4: return .zo4
        case .zo6: return .zo6
        case .zoe1: return .zoe1
        case .zoek2: return .zoek2
        case .zoek3: return .zoek3
        case .zoek6: return .zoek6
        case .zoeng1: return .zoeng1
        case .zoeng2: return .zoeng2
        case .zoeng3: return .zoeng3
        case .zoeng6: return .zoeng6
        case .zoi1: return .zoi1
        case .zoi2: return .zoi2
        case .zoi3: return .zoi3
        case .zoi6: return .zoi6
        case .zok2: return .zok2
        case .zok3: return .zok3
        case .zok6: return .zok6
        case .zong1: return .zong1
        case .zong2: return .zong2
        case .zong3: return .zong3
        case .zong5: return .zong5
        case .zong6: return .zong6
        case .zou1: return .zou1
        case .zou2: return .zou2
        case .zou3: return .zou3
        case .zou6: return .zou6
        case .zuk1: return .zuk1
        case .zuk3: return .zuk3
        case .zuk6: return .zuk6
        case .zung1: return .zung1
        case .zung2: return .zung2
        case .zung3: return .zung3
        case .zung6: return .zung6
        case .zyu1: return .zyu1
        case .zyu2: return .zyu2
        case .zyu3: return .zyu3
        case .zyu6: return .zyu6
        case .zyun1: return .zyun1
        case .zyun2: return .zyun2
        case .zyun3: return .zyun3
        case .zyun6: return .zyun6
        case .zyut1: return .zyut1
        case .zyut2: return .zyut2
        case .zyut3: return .zyut3
        case .zyut6: return .zyut6
        }
    }
}
